allowBuilds:
    '@parcel/watcher': true
    esbuild: true
    pnpm: true
    sharp: true
    unrs-resolver: true
    vue-demi: true
minimumReleaseAgeExclude:
    - '@iconify-json/material-symbols@1.2.80'
