import { describe, expect, it } from 'vitest'
import { parseMetadataFromName } from '../../../../server/services/media-name-parser'

describe('media name parser', () => {
    it.each([
        {
            name: 'parses tv release metadata from a scene-style name',
            input: 'The.Show.S02E03.1080p.WEB-DL.NF.REPACK.PROPER.HYBRID-NTb',
            expected: {
                season: 2,
                episode: 3,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'NF',
                cut: undefined,
                ratio: undefined,
                repack: 1,
                proper: 1,
                rerip: 0,
                hybrid: true,
                releaseGroup: 'NTb',
                title: 'The Show',
            },
        },
        {
            name: 'parses movie metadata with cut and remux/source markers',
            input: "Movie.Title.2001.Director's.Cut.REMUX.BluRay-AMZN",
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'REMUX',
                source: 'BluRay',
                service: 'AMZN',
                cut: "Director's Cut",
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'AMZN',
                title: 'Movie Title',
            },
        },
        {
            name: 'defaults to encode + bluray + no service when markers are absent',
            input: 'Simple.Name-Group',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'Group',
                title: 'Simple Name',
            },
        },
        {
            name: 'parses webrip source type and web source',
            input: 'Some.Movie.2010.WEBRIP-AMZN',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'WEBRIP',
                source: 'Web',
                service: 'AMZN',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'AMZN',
                title: 'Some Movie',
            },
        },
        {
            name: 'parses webdl token source type',
            input: 'Some.Movie.2010.WEBDL-AMZN',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'AMZN',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'AMZN',
                title: 'Some Movie',
            },
        },
        {
            name: 'parses hdtv source',
            input: 'Show.S01E01.HDTV-LOL',
            expected: {
                season: 1,
                episode: 1,
                sourceType: 'HDTV',
                source: 'HDTV',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'LOL',
                title: 'Show',
            },
        },
        {
            name: 'parses uhdtv source',
            input: 'Show.S01E01.UHDTV-LOL',
            expected: {
                season: 1,
                episode: 1,
                sourceType: 'HDTV',
                source: 'UHDTV',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'LOL',
                title: 'Show',
            },
        },
        {
            name: 'parses dvd source fallback as DVD when no NTSC or PAL prefix',
            input: 'Old.Movie.Extended.DVD',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'DVD',
                service: undefined,
                cut: 'Extended',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: '',
                title: 'Old Movie Extended DVD',
            },
        },
        {
            name: 'parses special edition cut',
            input: 'Film.Title.Special.Edition-BTN',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: 'Special Edition',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'BTN',
                title: 'Film Title Special Edition',
            },
        },
        {
            name: 'parses unrated cut',
            input: 'Film.Title.Unrated-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: 'Unrated',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Film Title Unrated',
            },
        },
        {
            name: 'parses 3D BluRay source from BluRay.3D token',
            input: 'Film.Title.BluRay.3D-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: '3D BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Film Title',
            },
        },
        {
            name: 'parses super duper cut',
            input: 'Film.Title.Super.Duper.Cut-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: 'Super Duper Cut',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Film Title Super Duper Cut',
            },
        },
        {
            name: 'when only contains season',
            input: '1899.S01.PROPER.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-FLUX',
            expected: {
                season: 1,
                episode: undefined,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'NF',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 1,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'FLUX',
                title: '1899',
            },
        },
        {
            name: 'when a service name is also in title',
            input: 'The.IT.Crowd.S01.1080p.ALL4.WEB-DL.AAC2.0.H.264-FFG',
            expected: {
                season: 1,
                episode: undefined,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'ALL4',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'FFG',
                title: 'The IT Crowd',
            },
        },
        {
            name: 'passes metadata from a file',
            input: 'Drive-Away.Dolls.2024.1080p.Blu-ray.Remux-AVC.TrueHD.Atmos.7.1-CiNEPHiLES.mkv',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'REMUX',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'CiNEPHiLES',
                title: 'Drive-Away Dolls',
            },
        },
        {
            name: '50.First.Dates.2004.BluRay.1080p.DTS-HD.MA.5.1.MPEG-2.REMUX-FraMeSToR',
            input: '50.First.Dates.2004.BluRay.1080p.DTS-HD.MA.5.1.MPEG-2.REMUX-FraMeSToR',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'REMUX',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'FraMeSToR',
                title: '50 First Dates',
            },
        },
        {
            name: 'does not strip invalid extension-like suffixes',
            input: 'Movie.Title.2024-GRP.字幕',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP.字幕',
                title: 'Movie Title',
            },
        },
        {
            name: 'does not strip extension when basename does not resemble a media name',
            input: 'Sample.mkv',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: '',
                title: 'Sample mkv',
            },
        },
        {
            name: 'keeps full filename title when no metadata markers are present',
            input: 'My.Sample.File-GRP.mkv',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'My Sample File',
            },
        },
        {
            name: 'parses RERIP flag',
            input: 'Movie.Title.2023.1080p.BluRay.RERIP-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 1,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses RERIP2 flag',
            input: 'Movie.Title.2023.1080p.BluRay.RERIP2-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 2,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses IMAX ratio',
            input: 'Movie.Title.2023.IMAX.1080p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: 'IMAX',
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses Open Matte ratio',
            input: 'Movie.Title.2023.Open.Matte.1080p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: 'Open Matte',
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses MAR ratio',
            input: 'Movie.Title.2023.MAR.1080p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: 'MAR',
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses REPACK2 and PROPER2 as number 2',
            input: 'The.Show.S01E01.1080p.WEB-DL.NF.REPACK2.PROPER2-GRP',
            expected: {
                season: 1,
                episode: 1,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'NF',
                cut: undefined,
                ratio: undefined,
                repack: 2,
                proper: 2,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'The Show',
            },
        },
        {
            name: 'parses NTSC DVD from NTSC token',
            input: 'Old.Movie.NTSC.DVD-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'NTSC DVD',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Old Movie NTSC DVD',
            },
        },
        {
            name: 'parses PAL DVD from PAL token',
            input: 'Old.Movie.PAL.DVD-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'PAL DVD',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Old Movie PAL DVD',
            },
        },
        {
            name: 'parses HD DVD source',
            input: 'Movie.Title.HD.DVD-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'HDDVD',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title HD DVD',
            },
        },
        {
            name: 'parses UHD BluRay from UHD.BluRay token in filename',
            input: 'Movie.Title.2023.2160p.UHD.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'UHD BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses BluRay source even when resolution is 2160p (UHD upgrade is a later stage concern)',
            input: 'Movie.Title.2023.2160p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'strips trailing closing parenthesis from release group in parenthesized tech-info filename',
            input: 'The Lord of the Rings - The Rings of Power (2022) S00E13 (1080p AMZN WEB-DL H265 SDR DDP 5.1 English - HONE).mkv',
            expected: {
                season: 0,
                episode: 13,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'AMZN',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'HONE',
                title: 'The Lord of the Rings - The Rings of Power',
            },
        },
    ])('$name', ({ input, expected }) => {
        expect(parseMetadataFromName(input)).toEqual(expected)
    })

    it.each([
        {
            name: 'parses episode range with E-prefixed end (S00E03-E08)',
            input: 'The.Good.Place.S00E03-E08.The.Selection.1080p.AMZN.WEB-DL.DDP.2.0.H.264-MRKT.mkv',
            expected: {
                season: 0,
                episode: 3,
                episodeEnd: 8,
                specialName: 'The Selection',
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'AMZN',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'MRKT',
                title: 'The Good Place',
            },
        },
        {
            name: 'parses episode range without E-prefix on end (S01E01-03)',
            input: 'Some.Show.S01E01-03.1080p.WEB-DL-GRP',
            expected: {
                season: 1,
                episode: 1,
                episodeEnd: 3,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: 0,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Some Show',
            },
        },
    ])('$name', ({ input, expected }) => {
        expect(parseMetadataFromName(input)).toEqual(expected)
    })

    it.each([
        {
            name: 'extracts special name for S00E## (TVDb special)',
            input: 'Top.Gear.S00E12.Polar.Challenge.1080i.DD2.0.AVC.REMUX-FraMeSToR.mkv',
            expectedSeason: 0,
            expectedEpisode: 12,
            expectedSpecialName: 'Polar Challenge',
        },
        {
            name: 'extracts special name for S##E00 (non-TVDb special)',
            input: 'Top.Gear.S27E00.Nepal.Special.1080p.iP.WEB-DL.AAC2.0.H.264-TBN.mkv',
            expectedSeason: 27,
            expectedEpisode: 0,
            expectedSpecialName: 'Nepal Special',
        },
        {
            name: 'strips cut from special name',
            input: "Top.Gear.S00E12.Polar.Challenge.Director's.Cut.1080i.REMUX-GRP.mkv",
            expectedSeason: 0,
            expectedEpisode: 12,
            expectedSpecialName: 'Polar Challenge',
        },
        {
            name: 'returns no special name for regular S##E## episodes',
            input: 'Top.Gear.S30E01.1080p.HDTV.H264-GRP.mkv',
            expectedSeason: 30,
            expectedEpisode: 1,
            expectedSpecialName: undefined,
        },
        {
            name: 'extracts special name when no technical marker follows (uses end of string)',
            input: 'Show.S00E01.Tribute-GRP',
            expectedSeason: 0,
            expectedEpisode: 1,
            expectedSpecialName: 'Tribute',
        },
        {
            name: 'returns undefined when only a cut token follows the SxxExx token',
            input: "Show.S00E01.Director's.Cut.1080p.REMUX-GRP",
            expectedSeason: 0,
            expectedEpisode: 1,
            expectedSpecialName: undefined,
        },
        {
            name: 'splits hyphenated word in special name into separate words',
            input: 'The.Lord.of.the.Rings.The.Rings.of.Power.S00E14.Stories.of.the.Second.Age.Khazad-dum.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv',
            expectedSeason: 0,
            expectedEpisode: 14,
            expectedEpisodeEnd: undefined,
            expectedSpecialName: 'Stories of the Second Age Khazad dum',
        },
        {
            name: 'extracts special name and episodeEnd for a multi-episode special range',
            input: 'The.Good.Place.S00E03-E08.The.Selection.1080p.AMZN.WEB-DL.DDP.2.0.H.264-MRKT.mkv',
            expectedSeason: 0,
            expectedEpisode: 3,
            expectedEpisodeEnd: 8,
            expectedSpecialName: 'The Selection',
        },
    ])('$name', ({ input, expectedSeason, expectedEpisode, expectedEpisodeEnd, expectedSpecialName }) => {
        const result = parseMetadataFromName(input)
        expect(result.season).toBe(expectedSeason)
        expect(result.episode).toBe(expectedEpisode)
        expect(result.episodeEnd).toBe(expectedEpisodeEnd)
        expect(result.specialName).toBe(expectedSpecialName)
    })
})
