import { describe, expect, it } from 'vitest'
import { parseMetadataFromName } from '../../../../server/services/media-name-parser'

describe('media name parser', () => {
    it.each([
        {
            name: 'parses tv release metadata from a scene-style name',
            input: 'The.Show.S02E03.1080p.WEB-DL.NF.REPACK.PROPER.HYBRID-NTb',
            expected: {
                season: 2,
                episode: 3,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'NF',
                cut: undefined,
                ratio: undefined,
                repack: 1,
                proper: 1,
                rerip: false,
                threeD: false,
                hybrid: true,
                releaseGroup: 'NTb',
                title: 'The Show',
            },
        },
        {
            name: 'parses movie metadata with cut and remux/source markers',
            input: "Movie.Title.2001.Director's.Cut.REMUX.BluRay-AMZN",
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'REMUX',
                source: 'BluRay',
                service: 'AMZN',
                cut: "Director's Cut",
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'AMZN',
                title: 'Movie Title',
            },
        },
        {
            name: 'defaults to encode + bluray + no service when markers are absent',
            input: 'Simple.Name-Group',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'Group',
                title: 'Simple Name',
            },
        },
        {
            name: 'parses webrip source type and web source',
            input: 'Some.Movie.2010.WEBRIP-AMZN',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'WEBRIP',
                source: 'Web',
                service: 'AMZN',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'AMZN',
                title: 'Some Movie',
            },
        },
        {
            name: 'parses webdl token source type',
            input: 'Some.Movie.2010.WEBDL-AMZN',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'AMZN',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'AMZN',
                title: 'Some Movie',
            },
        },
        {
            name: 'parses hdtv source type',
            input: 'Show.S01E01.HDTV-LOL',
            expected: {
                season: 1,
                episode: 1,
                sourceType: 'HDTV',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'LOL',
                title: 'Show',
            },
        },
        {
            name: 'parses dvd source fallback and no release group',
            input: 'Old.Movie.Extended.DVD',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'DVD',
                service: undefined,
                cut: 'Extended',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: '',
                title: 'Old Movie Extended DVD',
            },
        },
        {
            name: 'parses special edition cut',
            input: 'Film.Title.Special.Edition-BTN',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: 'Special Edition',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'BTN',
                title: 'Film Title Special Edition',
            },
        },
        {
            name: 'parses unrated cut',
            input: 'Film.Title.Unrated-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: 'Unrated',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Film Title Unrated',
            },
        },
        {
            name: 'parses 3D flag',
            input: 'Film.Title.3D-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: true,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Film Title 3D',
            },
        },
        {
            name: 'parses super duper cut',
            input: 'Film.Title.Super.Duper.Cut-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: 'Super Duper Cut',
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Film Title Super Duper Cut',
            },
        },
        {
            name: 'when only contains season',
            input: '1899.S01.PROPER.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-FLUX',
            expected: {
                season: 1,
                episode: undefined,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'NF',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 1,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'FLUX',
                title: '1899',
            },
        },
        {
            name: 'when a service name is also in title',
            input: 'The.IT.Crowd.S01.1080p.ALL4.WEB-DL.AAC2.0.H.264-FFG',
            expected: {
                season: 1,
                episode: undefined,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'ALL4',
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'FFG',
                title: 'The IT Crowd',
            },
        },
        {
            name: 'passes metadata from a file',
            input: 'Drive-Away.Dolls.2024.1080p.Blu-ray.Remux-AVC.TrueHD.Atmos.7.1-CiNEPHiLES.mkv',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'REMUX',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'CiNEPHiLES',
                title: 'Drive-Away Dolls',
            },
        },
        {
            name: '50.First.Dates.2004.BluRay.1080p.DTS-HD.MA.5.1.MPEG-2.REMUX-FraMeSToR',
            input: '50.First.Dates.2004.BluRay.1080p.DTS-HD.MA.5.1.MPEG-2.REMUX-FraMeSToR',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'REMUX',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'FraMeSToR',
                title: '50 First Dates',
            },
        },
        {
            name: 'does not strip invalid extension-like suffixes',
            input: 'Movie.Title.2024-GRP.字幕',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP.字幕',
                title: 'Movie Title',
            },
        },
        {
            name: 'does not strip extension when basename does not resemble a media name',
            input: 'Sample.mkv',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: '',
                title: 'Sample mkv',
            },
        },
        {
            name: 'keeps full filename title when no metadata markers are present',
            input: 'My.Sample.File-GRP.mkv',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'My Sample File',
            },
        },
        {
            name: 'parses RERIP flag',
            input: 'Movie.Title.2023.1080p.BluRay.RERIP-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: undefined,
                repack: 0,
                proper: 0,
                rerip: true,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses IMAX ratio',
            input: 'Movie.Title.2023.IMAX.1080p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: 'IMAX',
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses Open Matte ratio',
            input: 'Movie.Title.2023.Open.Matte.1080p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: 'Open Matte',
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses MAR ratio',
            input: 'Movie.Title.2023.MAR.1080p.BluRay-GRP',
            expected: {
                season: undefined,
                episode: undefined,
                sourceType: 'ENCODE',
                source: 'BluRay',
                service: undefined,
                cut: undefined,
                ratio: 'MAR',
                repack: 0,
                proper: 0,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'Movie Title',
            },
        },
        {
            name: 'parses REPACK2 and PROPER2 as number 2',
            input: 'The.Show.S01E01.1080p.WEB-DL.NF.REPACK2.PROPER2-GRP',
            expected: {
                season: 1,
                episode: 1,
                sourceType: 'WEB-DL',
                source: 'Web',
                service: 'NF',
                cut: undefined,
                ratio: undefined,
                repack: 2,
                proper: 2,
                rerip: false,
                threeD: false,
                hybrid: false,
                releaseGroup: 'GRP',
                title: 'The Show',
            },
        },
    ])('$name', ({ input, expected }) => {
        expect(parseMetadataFromName(input)).toEqual(expected)
    })
})
